# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User'),
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(help_text='add product to shop', related_name='shops', to='merchandizers.Product'),
        ),
        migrations.AddField(
            model_name='shop',
            name='setting',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'shop'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='merchandizers.merchandizersetting'),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated User'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User'),
        ),
        migrations.AddField(
            model_name='product',
            name='setting',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='merchandizers.merchandizersetting'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated User'),
        ),
        migrations.AddField(
            model_name='pricetracking',
            name='merchandizer_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_price_tracking', to='merchandizers.merchandizerproduct'),
        ),
        migrations.AddField(
            model_name='merchandizersetting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandizer_settings', to='managements.client'),
        ),
        migrations.AddField(
            model_name='merchandizersetting',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='merchandizers.merchandizersetting'),
        ),
        migrations.AddField(
            model_name='merchandizerproduct',
            name='merchandizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandizer_products', to='merchandizers.merchandizer'),
        ),
        migrations.AddField(
            model_name='merchandizerproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandizer_products', to='merchandizers.product'),
        ),
        migrations.AddField(
            model_name='merchandizer',
            name='employee_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandizers', to='users.employeeproject'),
        ),
        migrations.AddField(
            model_name='merchandizer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandizers', to='merchandizers.shop'),
        ),
        migrations.AddConstraint(
            model_name='merchandizersetting',
            constraint=models.UniqueConstraint(condition=models.Q(('alive', True)), fields=('name', 'type', 'level_name', 'client'), name='unique-name-type-setting-level-client'),
        ),
        migrations.AddConstraint(
            model_name='merchandizerproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('alive', True)), fields=('merchandizer', 'product'), name='unique-merchandizer-product'),
        ),
        migrations.AddConstraint(
            model_name='merchandizer',
            constraint=models.UniqueConstraint(condition=models.Q(('alive', True)), fields=('employee_project', 'shop'), name='unique-employee-project-shop'),
        ),
    ]
