# Generated by Django 3.2.5 on 2022-05-23 08:43

from django.db import migrations, models
import django.db.models.deletion
import model_controller.fields


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_initial'),
        ('merchandizers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandizerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', model_controller.fields.LiveField(db_index=True, default=True, null=True)),
                ('type', models.CharField(choices=[('shop', 'Shop'), ('product', 'Product')], help_text='type of detail question shop or product', max_length=7)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandizer_questions', to='managements.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', model_controller.fields.LiveField(db_index=True, default=True, null=True)),
                ('question_name', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, limit_choices_to={'type': 'shop'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_details', to='merchandizers.merchandizerquestion')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_details', to='merchandizers.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', model_controller.fields.LiveField(db_index=True, default=True, null=True)),
                ('question_name', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='merchandizers.product')),
                ('question', models.ForeignKey(blank=True, limit_choices_to={'type': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='merchandizers.merchandizerquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shopdetail',
            constraint=models.UniqueConstraint(condition=models.Q(('alive', True)), fields=('shop', 'question'), name='unique-shop-question'),
        ),
        migrations.AddConstraint(
            model_name='productdetail',
            constraint=models.UniqueConstraint(condition=models.Q(('alive', True)), fields=('product', 'question'), name='unique-product-question'),
        ),
    ]
