# Generated by Django 3.2.5 on 2022-05-24 06:29

from django.db import migrations, models
import django.db.models.deletion
import model_controller.fields


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_initial'),
        ('merchandizers', '0003_auto_20220523_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTrackingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', model_controller.fields.LiveField(db_index=True, default=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_tracking_settings', to='managements.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
