# Generated by Django 3.2.5 on 2022-05-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandizers', '0004_pricetrackingsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetracking',
            name='reason',
            field=models.ForeignKey(help_text='for type no promotion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='merchandizers.pricetrackingsetting'),
        ),
    ]
