# Generated by Django 3.2.5 on 2022-05-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_initial'),
        ('merchandizers', '0005_alter_pricetracking_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetrackingsetting',
            name='client',
        ),
        migrations.AddField(
            model_name='pricetrackingsetting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_tracking_settings', to='managements.project'),
        ),
    ]
