version: "2.4"

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - ./.docker_volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0-alpine
    volumes:
      - ./.docker_volumes/redis:/data

  django:
    depends_on:
      - postgres
      - redis

  celery-worker:
    command: sh -c "pip install -r requirements.txt && celery -A main worker -l INFO"

  celery-beat:
    command: sh -c "pip install -r requirements.txt && celery -A main beat -l INFO --pidfile="

  mocki:
    image: node:14-alpine3.11
    volumes:
      - ./mocki.yml:/mocki.yml
    command: sh -c "npm install -g mocki && mocki run --path /mocki.yml"
