name: ahead_adecco
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.4+13

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # Config
  get: ^4.6.3
  package_info_plus: ^1.4.0
  device_info_plus: ^3.2.2

  # Util
  sentry_flutter: ^6.4.0
  keyboard_dismisser: ^2.0.0
  pin_code_fields: ^7.3.0
  flutter_launcher_icons: ^0.9.2
  auto_size_text: ^3.0.0
  file_picker: ^4.3.3
  flutter_native_splash: ^2.1.2+1
  permission_handler: ^9.2.0
  camera: ^0.9.4+20
  location: ^4.3.0
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  hive: ^2.2.1
  sizer: ^2.0.15
  connectivity_plus: ^2.2.0
  webview_flutter: ^3.0.0
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  image_picker: ^0.8.5
  safe_device: ^1.1.0
  encrypt: ^5.0.1
  equatable: ^2.0.3
  flutter_datetime_picker: 
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  scroll_to_index: ^2.1.1
  jiffy: ^5.0.0
  loader_overlay: ^2.0.6
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  flutter_multi_formatter: ^2.5.7

  # Widget
  syncfusion_flutter_gauges: ^20.1.55
  dropdown_button2: ^1.1.0
  table_calendar: ^3.0.5
  modal_bottom_sheet: ^2.0.0
  dotted_border: ^2.0.0+2
  percent_indicator: ^4.0.0
  flutter_spinkit: ^5.1.0
  day_night_time_picker: ^1.0.5
  multi_select_flutter: ^4.1.2
  custom_map_markers: ^0.0.2+1

  # Image
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter_icons:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path: "assets/images/icon_launcher.png"


flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/icons/
      - assets/images/emoji/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt-Light.ttf
        - asset: assets/fonts/Prompt-Regular.ttf

    - family: HouschkaHead
      fonts:
        - asset: assets/fonts/HouschkaHead-Bold.otf
        - asset: assets/fonts/HouschkaHead-Light.otf
        - asset: assets/fonts/HouschkaHead-Medium.otf