# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.db import migrations, models
import django.db.models.deletion
import main.apps.common.minio
import model_controller.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('check_in', 'Check in'), ('check_out', 'Check out'), ('pin_point', 'Pin Point'), ('track_route', 'Track Route')], max_length=20)),
                ('extra_type', models.CharField(choices=[('absent', 'Absent'), ('late', 'Late'), ('personal_leave', 'Personal Leave'), ('sick_leave', 'Sick Leave'), ('ot', 'OT'), ('early_leave', 'Early Leave')], max_length=20, null=True)),
                ('date_time', models.DateTimeField()),
                ('location_name', models.TextField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('picture', models.ImageField(storage=main.apps.common.minio.SwitchMinioBackend(bucket_name='django-media'), upload_to='activities/images/%Y-%m-%d/')),
                ('reason_for_adjust_time', models.TextField(blank=True, null=True)),
                ('reason_for_adjust_status', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('in_radius', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckInOutPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_name', models.CharField(max_length=200)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('alive', model_controller.fields.LiveField(db_index=True, default=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('history', 'History'), ('approve', 'Approve'), ('partial_approve', 'Partial-Approve'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestPartialApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('earn_income', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apply_before', models.PositiveSmallIntegerField(default=30, null=True)),
                ('apply_after', models.PositiveSmallIntegerField(default=30, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('alive', model_controller.fields.LiveField(db_index=True, default=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('multi_day', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('partial_approve', 'Partial-Approve'), ('reject', 'Reject')], default='pending', max_length=15)),
                ('type', models.CharField(choices=[('user_request', 'User request'), ('assign_ot', 'Assign OT')], default='user_request', max_length=12)),
                ('note', models.TextField(blank=True, help_text='note for approve', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for reject', null=True)),
                ('partial_start_time', models.TimeField(help_text='For partial approve', null=True)),
                ('partial_end_time', models.TimeField(help_text='For partial approve', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PinPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='activities/leave-files/%Y-%m-%d/')),
                ('leave_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_attachments', to='activities.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='PinPointAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('pin_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='activities.pinpoint')),
            ],
        ),
    ]
