# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinpointanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='managements.pinpointquestion'),
        ),
        migrations.AddField(
            model_name='pinpoint',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_point', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='pinpoint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='managements.pinpointtype'),
        ),
        migrations.AddField(
            model_name='otrequest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_requests', to='managements.project'),
        ),
    ]
