# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otrequest',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='managements.workplace'),
        ),
        migrations.AddField(
            model_name='leavetypesetting',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_settings', to='managements.client'),
        ),
        migrations.AddField(
            model_name='leavetypesetting',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_settings', to='managements.project'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_types', to='managements.client'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='leave_type_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='activities.leavetypesetting'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_types', to='managements.project'),
        ),
        migrations.AddField(
            model_name='leaverequestpartialapprove',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_partial_approves', to='activities.leaverequest'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='managements.project'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='activities.leavetype'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to='managements.project'),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_quotas', to='activities.leavetype'),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to='activities.place'),
        ),
        migrations.AddField(
            model_name='checkinoutpair',
            name='check_in',
            field=models.OneToOneField(help_text='pair check in', limit_choices_to={'type': 'check_in'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_pair', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='checkinoutpair',
            name='check_out',
            field=models.OneToOneField(help_text='pair check out', limit_choices_to={'type': 'check_out'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_pair', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='managements.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='working_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='managements.workinghour'),
        ),
        migrations.AddField(
            model_name='activity',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='managements.workplace'),
        ),
        migrations.AddConstraint(
            model_name='leavequota',
            constraint=models.UniqueConstraint(fields=('type', 'project', 'user'), name='unique-leave_quota'),
        ),
    ]
