# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.db import migrations, models
import django.db.models.deletion
import model_controller.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', model_controller.fields.LiveField(db_index=True, default=True, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('edit_pending', 'Edit pending'), ('reject', 'Reject'), ('edit_reject', 'Edit reject'), ('approve', 'Approve'), ('waiting_for_delete', 'Waiting for delete'), ('delete', 'Delete')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DayOffDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EditShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('approve', 'Approve')], default='pending', max_length=20)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('shift', 'Shift'), ('day_off', 'Day off')], default='shift', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('approve', 'Approve')], default='pending', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('roster_setting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('edit_pending', 'Edit pending'), ('reject', 'Reject'), ('edit_reject', 'Edit reject'), ('approve', 'Approve'), ('waiting_for_delete', 'Waiting for delete'), ('delete', 'Delete')], default='pending', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('roster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='rosters.roster')),
                ('working_hour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='managements.workinghour')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('monday', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('tuesday', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('wednesday', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('thursday', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('friday', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('saturday', models.CharField(choices=[('holiday', 'Holiday'), ('work_day', 'Work day'), ('day_off', 'Day off')], max_length=10)),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='rosters.shift')),
                ('workplaces', models.ManyToManyField(related_name='_rosters_schedule_workplaces_+', to='managements.WorkPlace')),
            ],
        ),
    ]
