# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0002_initial'),
        ('users', '0001_initial'),
        ('rosters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='employee_projects',
            field=models.ManyToManyField(related_name='rosters', to='users.EmployeeProject'),
        ),
        migrations.AddField(
            model_name='editshift',
            name='from_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rosters.shift'),
        ),
        migrations.AddField(
            model_name='editshift',
            name='to_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rosters.shift'),
        ),
        migrations.AddField(
            model_name='dayoffdetail',
            name='day_off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='rosters.dayoff'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='roster',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_off', to='rosters.roster'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='working_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_offs', to='managements.workinghour'),
        ),
        migrations.AddField(
            model_name='adjustrequest',
            name='employee_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjust_requests', to='users.employeeproject'),
        ),
        migrations.AddField(
            model_name='adjustrequest',
            name='working_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='managements.workinghour'),
        ),
        migrations.AddField(
            model_name='adjustrequest',
            name='workplaces',
            field=models.ManyToManyField(related_name='_rosters_adjustrequest_workplaces_+', to='managements.WorkPlace'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('sunday', 'work_day')), fields=('shift', 'sunday'), name='unique-shift-sunday-working'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('monday', 'work_day')), fields=('shift', 'monday'), name='unique-shift-monday-working'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('tuesday', 'work_day')), fields=('shift', 'tuesday'), name='unique-shift-tuesday-working'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('wednesday', 'work_day')), fields=('shift', 'wednesday'), name='unique-shift-wednesday-working'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('thursday', 'work_day')), fields=('shift', 'thursday'), name='unique-shift-thursday-working'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('friday', 'work_day')), fields=('shift', 'friday'), name='unique-shift-friday-working'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('saturday', 'work_day')), fields=('shift', 'saturday'), name='unique-shift-saturday-working'),
        ),
    ]
