# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('pay_code', models.CharField(max_length=255)),
                ('day_of_week', models.CharField(choices=[('working_day', 'Working day'), ('day_off', 'Day off')], max_length=11)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('default_holiday', 'Default holiday'), ('custom_holiday', 'Custom holiday')], max_length=15)),
                ('date', models.DateField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_th', models.TextField(blank=True, null=True)),
                ('branch', models.TextField()),
                ('contact_person', models.TextField()),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('ot_quota', models.PositiveSmallIntegerField(help_text='OT quota (in minutes)', null=True)),
                ('lead_time_in_before', models.PositiveSmallIntegerField(default=30, help_text='Lead time in before (in minutes)', null=True)),
                ('lead_time_in_after', models.PositiveSmallIntegerField(default=30, help_text='Lead time in after (in minutes)', null=True)),
                ('lead_time_out_before', models.PositiveSmallIntegerField(default=30, help_text='Lead time out before (in minutes)', null=True)),
                ('lead_time_out_after', models.PositiveSmallIntegerField(default=30, help_text='Lead time out after (in minutes)', null=True)),
                ('business_calendar_type', models.CharField(choices=[('default_holiday', 'Default holiday'), ('custom_holiday', 'Custom holiday')], default='default_holiday', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OTRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('pay_code', models.DecimalField(decimal_places=2, max_digits=4)),
                ('day', models.CharField(choices=[('working_day', 'Working day'), ('day_off', 'Day off')], max_length=11)),
                ('time', models.CharField(choices=[('normal_work_hour', 'Normal work hour'), ('over_normal_time', 'Over normal time')], max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinPointQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('require', models.BooleanField(default=True)),
                ('hide', models.BooleanField(default=False)),
                ('template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PinPointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('ot_quota', models.PositiveSmallIntegerField(help_text='OT quota (in minutes)', null=True)),
                ('lead_time_in_before', models.PositiveSmallIntegerField(default=30, help_text='Lead time in before (in minutes)', null=True)),
                ('lead_time_in_after', models.PositiveSmallIntegerField(default=30, help_text='Lead time in after (in minutes)', null=True)),
                ('lead_time_out_before', models.PositiveSmallIntegerField(default=30, help_text='Lead time out before (in minutes)', null=True)),
                ('lead_time_out_after', models.PositiveSmallIntegerField(default=30, help_text='Lead time out after (in minutes)', null=True)),
                ('business_calendar_type', models.CharField(choices=[('default_holiday', 'Default holiday'), ('custom_holiday', 'Custom holiday')], default='default_holiday', max_length=15)),
                ('feature_check_in_check_out', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_roster_plan', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_leave_request', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_ot_request', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_todo', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_track_route_pin_point', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_osa_oss', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_price_tracking', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_sku', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_sales_report', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_event_stock', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('feature_survey', models.CharField(choices=[('disable', 'Disable'), ('adecco_only', 'Adecco only'), ('adecco_and_client', 'Adecco and client')], default='disable', max_length=17)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='managements.client')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('wifi', models.TextField(blank=True, null=True)),
                ('bluetooth', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('addition_note', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('radius_meter', models.PositiveIntegerField(default=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplaces', to='managements.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday_start_time', models.TimeField(null=True)),
                ('sunday_end_time', models.TimeField(null=True)),
                ('monday_start_time', models.TimeField(null=True)),
                ('monday_end_time', models.TimeField(null=True)),
                ('tuesday_start_time', models.TimeField(null=True)),
                ('tuesday_end_time', models.TimeField(null=True)),
                ('wednesday_start_time', models.TimeField(null=True)),
                ('wednesday_end_time', models.TimeField(null=True)),
                ('thursday_start_time', models.TimeField(null=True)),
                ('thursday_end_time', models.TimeField(null=True)),
                ('friday_start_time', models.TimeField(null=True)),
                ('friday_end_time', models.TimeField(null=True)),
                ('saturday_start_time', models.TimeField(null=True)),
                ('saturday_end_time', models.TimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='managements.client')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='managements.project')),
            ],
        ),
    ]
