# Generated by Django 3.2.5 on 2022-05-22 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignee_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(limit_choices_to={'role__in': ['project_manager', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinpointtype',
            name='employee_projects',
            field=models.ManyToManyField(related_name='pin_point_types', to='users.EmployeeProject'),
        ),
        migrations.AddField(
            model_name='pinpointtype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_point_types', to='managements.project'),
        ),
        migrations.AddField(
            model_name='pinpointquestion',
            name='pin_point_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='managements.pinpointtype'),
        ),
        migrations.AddField(
            model_name='otrule',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_rules', to='managements.client'),
        ),
        migrations.AddField(
            model_name='otrule',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_rules', to='managements.project'),
        ),
        migrations.AddField(
            model_name='client',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesscalendar',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_calendars', to='managements.client'),
        ),
        migrations.AddField(
            model_name='businesscalendar',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_calendars', to='managements.project'),
        ),
        migrations.AddField(
            model_name='additionalallowance',
            name='working_hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_allowances', to='managements.workinghour'),
        ),
        migrations.AddConstraint(
            model_name='otrule',
            constraint=models.UniqueConstraint(fields=('client', 'day', 'time'), name='unique-client-day-time'),
        ),
        migrations.AddConstraint(
            model_name='otrule',
            constraint=models.UniqueConstraint(fields=('project', 'day', 'time'), name='unique-project-day-time'),
        ),
        migrations.AddConstraint(
            model_name='businesscalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('client', 'type', 'date'), name='unique-client-type-date'),
        ),
    ]
